In [6]:
import pandas as pd
import numpy as np
import math
M = np.array([[1,3,5,5,0],
              [3,0,0,4,2],
              [5,1,0,5,3]])
print("-----MA TRẬN BAN ĐẦU-----\n",M)

def matr(A,K,ite,b,lamda):
    #khoi tao ma tran W,H                    
    U = A.shape[0] #columns
   
    I = A.shape[1] #rows
    W = np.random.randn(U,K)
    H = np.random.randn(K,I)
    for j in range(ite):
        for u in range(U):
            for i in range(I):
                if (A[u,i]>0):
                    r_bav=0
                    for k in range (K):
                        r_bav = r_bav + np.dot(W[u,k],H[k,i]);
                    e = A[u,i] - r_bav
                    for k in range (K):
                        W[u,k] +=  2*b*(e * H[k,i] - lamda*W[u,k])
                        H[k,i] +=  2*b*(e * W[u,k] -lamda*H[k,i])             
    return np.dot(W,H)
v = matr(M,2,1000, 0.01,0.01);

print("-----MA TRẬN DỰ ĐOÁN-----\n",v)
print("----------------------------------------------------")
print("-----MA TRẬN DỰ ĐOÁN LÀM TRÒN-----\n",np.around(v))
                

-----MA TRẬN BAN ĐẦU-----
 [[1 3 5 5 0]
 [3 0 0 4 2]
 [5 1 0 5 3]]
-----MA TRẬN DỰ ĐOÁN-----
 [[1.01312778 2.98601568 4.98853507 4.98276426 1.39201696]
 [2.99354739 1.29482619 3.77581494 3.98877643 1.99525039]
 [4.9745933  1.0012395  4.59898384 4.9880284  2.99200054]]
----------------------------------------------------
-----MA TRẬN DỰ ĐOÁN LÀM TRÒN-----
 [[1. 3. 5. 5. 1.]
 [3. 1. 4. 4. 2.]
 [5. 1. 5. 5. 3.]]
